CraftyBrewBundle:
    resource:                           "@WebBundle/Resources/config/routing.yml"
    prefix:                             /
    schemes:                            [ https ]
    options:
        utf8:                           true
